export const merchCategories = [
  "moc khoa",
  "ao thun",
  "hoodie",
  "mu non",
  "sticker",
  "balo tui",
  "ly coc",
  "poster",
  "figure",
  "collector box",
] as const;

export const merchTemplates = [
  {
    title: "Moc Khoa Raptor Limited",
    slug: "moc-khoa-raptor-limited",
    price: 12,
    rating: 5,
    description: "Moc khoa kim loai hinh Raptor, phien ban collector set cua Dao Khung Long.",
    mainImage: "merch/product-keychain.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 32,
    isCollector: true,
  },
  {
    title: "Ao Thun Volcano T-Rex",
    slug: "ao-thun-volcano-trex",
    price: 29,
    rating: 5,
    description: "Ao thun cotton den, in T-Rex va nui lua cam theo style merch chinh hang.",
    mainImage: "merch/product-shirt.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "ao thun" },
    inStock: 18,
    isCollector: true,
  },
  {
    title: "Hoodie Amber Island",
    slug: "hoodie-amber-island",
    price: 59,
    rating: 5,
    description: "Hoodie day dan, tone den cam, thiet ke Amber Island cho fan sinh ton.",
    mainImage: "merch/product-hoodie.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "hoodie" },
    inStock: 14,
    isCollector: false,
  },
  {
    title: "Mu Non Dino Crew",
    slug: "mu-non-dino-crew",
    price: 24,
    rating: 4,
    description: "Mu non den voi logo Dino Crew theu cam, de doi hang ngay.",
    mainImage: "merch/product-cap.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "mu non" },
    inStock: 25,
    isCollector: false,
  },
  {
    title: "Sticker Pack Lava Run",
    slug: "sticker-pack-lava-run",
    price: 9,
    rating: 5,
    description: "Bo sticker chong nuoc gom T-Rex, dau chan khung long va dung nham.",
    mainImage: "merch/product-sticker.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "sticker" },
    inStock: 45,
    isCollector: false,
  },
  {
    title: "Balo Explorer Fossil",
    slug: "balo-explorer-fossil",
    price: 49,
    rating: 4,
    description: "Balo merch dung laptop, phu kien va collector gear cho chuyen di san.",
    mainImage: "merch/product-bag.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "balo tui" },
    inStock: 12,
    isCollector: false,
  },
  {
    title: "Ly Su Jurassic Flame",
    slug: "ly-su-jurassic-flame",
    price: 18,
    rating: 5,
    description: "Ly su den nham, logo Jurassic Flame doi mau cam khi uong nong.",
    mainImage: "merch/product-mug.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "ly coc" },
    inStock: 22,
    isCollector: false,
  },
  {
    title: "Poster T-Rex Volcano",
    slug: "poster-trex-volcano",
    price: 15,
    rating: 5,
    description: "Poster cinematic T-Rex va nui lua, in giay day cho goc setup.",
    mainImage: "merch/product-poster.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "poster" },
    inStock: 30,
    isCollector: false,
  },
  {
    title: "Figure Baby Raptor",
    slug: "figure-baby-raptor",
    price: 39,
    rating: 5,
    description: "Figure Baby Raptor de ban, mau doc quyen cua dot merch dau tien.",
    mainImage: "merch/product-figure.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "figure" },
    inStock: 5,
    isCollector: true,
  },
  {
    title: "Collector Box Amber Island",
    slug: "collector-box-amber-island",
    price: 79,
    rating: 5,
    description: "Hop collector gom pin, sticker, moc khoa va ma phan thuong trong game.",
    mainImage: "merch/product-box.svg",
    manufacturer: "Dao Khung Long",
    category: { name: "collector box" },
    inStock: 4,
    isCollector: true,
  },
] as const;

const hashString = (value: string) =>
  value.split("").reduce((total, char) => total + char.charCodeAt(0), 0);

export function toMerchProduct(product: Product, index?: number): Product {
  const template = merchTemplates[
    typeof index === "number" ? index % merchTemplates.length : hashString(product.id || product.slug) % merchTemplates.length
  ];

  return {
    ...product,
    title: template.title,
    slug: product.slug,
    price: template.price,
    rating: template.rating,
    description: template.description,
    mainImage: template.mainImage,
    manufacturer: template.manufacturer,
    category: template.category,
    inStock: template.inStock,
    isCollector: template.isCollector,
  };
}

export const fallbackMerchProducts = merchTemplates.map((template, index) => ({
  id: `fallback-merch-${index}`,
  slug: template.slug,
  title: template.title,
  price: template.price,
  rating: template.rating,
  description: template.description,
  mainImage: template.mainImage,
  manufacturer: template.manufacturer,
  categoryId: "fallback",
  category: template.category,
  inStock: template.inStock,
  isCollector: template.isCollector,
})) satisfies Product[];
