export const merchCategories = [
  "moc khoa",
  "ao thun",
  "hoodie",
  "mu non",
  "sticker",
  "balo tui",
  "ly coc",
  "poster",
  "figure",
  "collector box",
] as const;

export const merchTemplates = [
  {
    title: "Moc Khoa Dino Candy Pink",
    slug: "moc-khoa-dino-candy-pink",
    price: 12,
    rating: 5,
    description: "Moc khoa acrylic khung long hong, hoa tiet trai tim va keo ngot de thuong.",
    mainImage: "images/mk1.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 32,
    isCollector: true,
  },
  {
    title: "Moc Khoa Lava Black",
    slug: "moc-khoa-lava-black",
    price: 14,
    rating: 5,
    description: "Moc khoa khung long den do voi hoa tiet lua, phong cach manh me.",
    mainImage: "images/mk2.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 18,
    isCollector: true,
  },
  {
    title: "Moc Khoa Sky Blue",
    slug: "moc-khoa-sky-blue",
    price: 13,
    rating: 5,
    description: "Moc khoa khung long xanh troi voi may va ngoi sao sang.",
    mainImage: "images/mk3.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 14,
    isCollector: false,
  },
  {
    title: "Moc Khoa Tiger Star",
    slug: "moc-khoa-tiger-star",
    price: 13,
    rating: 4,
    description: "Moc khoa khung long vang cam voi soc ho va hoa tiet ngoi sao.",
    mainImage: "images/mk4.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 25,
    isCollector: false,
  },
  {
    title: "Moc Khoa Jungle Ricon",
    slug: "moc-khoa-jungle-ricon",
    price: 15,
    rating: 5,
    description: "Moc khoa khung long xanh la voi hoa tiet la cay va logo Ricon.",
    mainImage: "images/mk5.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 45,
    isCollector: false,
  },
  {
    title: "Moc Khoa Mint Garden",
    slug: "moc-khoa-mint-garden",
    price: 12,
    rating: 4,
    description: "Moc khoa khung long xanh mint voi hoa la nhe nhang.",
    mainImage: "images/mk6.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 12,
    isCollector: false,
  },
  {
    title: "Moc Khoa Moon Purple",
    slug: "moc-khoa-moon-purple",
    price: 14,
    rating: 5,
    description: "Moc khoa khung long tim voi trang khuyet va hoa tiet anh sao.",
    mainImage: "images/mk7.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 22,
    isCollector: false,
  },
  {
    title: "Moc Khoa Ice Ricon",
    slug: "moc-khoa-ice-ricon",
    price: 15,
    rating: 5,
    description: "Moc khoa khung long bang tuyet voi logo Ricon va bong tuyet.",
    mainImage: "images/mk8.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 30,
    isCollector: false,
  },
  {
    title: "Moc Khoa Dragon Violet",
    slug: "moc-khoa-dragon-violet",
    price: 16,
    rating: 5,
    description: "Moc khoa khung long tim dam voi hoa tiet rong vang, phien ban dac biet.",
    mainImage: "images/mk9.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 5,
    isCollector: true,
  },
  {
    title: "Moc Khoa Royal Black",
    slug: "moc-khoa-royal-black",
    price: 17,
    rating: 5,
    description: "Moc khoa khung long den vang voi vuong mien, mau collector sang trong.",
    mainImage: "images/mk10.png",
    manufacturer: "Dao Khung Long",
    category: { name: "moc khoa" },
    inStock: 4,
    isCollector: true,
  },
] as const;

const hashString = (value: string) =>
  value.split("").reduce((total, char) => total + char.charCodeAt(0), 0);

export const isMerchTemplateImage = (image?: string | null) =>
  Boolean(image?.startsWith("merch/") || image?.startsWith("images/mk"));

export function toMerchProduct(product: Product, index?: number): Product {
  const template = merchTemplates[
    typeof index === "number" ? index % merchTemplates.length : hashString(product.id || product.slug) % merchTemplates.length
  ];

  return {
    ...product,
    title: template.title,
    slug: product.slug,
    price: template.price,
    rating: template.rating,
    description: template.description,
    mainImage: template.mainImage,
    manufacturer: template.manufacturer,
    category: template.category,
    inStock: template.inStock,
    isCollector: template.isCollector,
  };
}

export const fallbackMerchProducts = merchTemplates.map((template, index) => ({
  id: `fallback-merch-${index}`,
  slug: template.slug,
  title: template.title,
  price: template.price,
  rating: template.rating,
  description: template.description,
  mainImage: template.mainImage,
  manufacturer: template.manufacturer,
  categoryId: "fallback",
  category: template.category,
  inStock: template.inStock,
  isCollector: template.isCollector,
})) satisfies Product[];
